# Generated by Django 5.2 on 2025-06-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id_movimiento', models.AutoField(db_column='id_movimiento', primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('cantidad_volatil', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Productos.producto')),
                ('vendedor', models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Empleados.empleado')),
            ],
            options={
                'db_table': 'movimientos_almacen',
            },
        ),
    ]
