# Generated by Django 5.2 on 2025-06-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=45)),
                ('carnet', models.CharField(max_length=16)),
                ('rol', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
